### ISSUE TITLE
爬取结果的储存位置

### ISSUE THREAD

**Issue by zskuhc** [huifeng-kooboo/weibo_keyword_crawl#7]
作者你好，怎么将爬取下来的结果保存在一个csv文件里呢？

**Comment by huifeng-kooboo** [comment]
里面有savecsv的逻辑 可以看看

**Comment by huifeng-kooboo** [comment]
> 

里面有savecsv的逻辑 可以看看

**Comment by Miaoz1** [comment]
您好请问在哪找到存储文件呀？我用pycharm点击运行main.py。进行完后我不知道在哪查看保存的数据，我也没有太看懂代码，请问大佬可以告诉我吗，谢谢！ @huifeng-kooboo

**Comment by huifeng-kooboo** [comment]
> 您好请问在哪找到存储文件呀？我用pycharm点击运行main.py。进行完后我不知道在哪查看保存的数据，我也没有太看懂代码，请问大佬可以告诉我吗，谢谢！ @huifeng-kooboo

这个得看有没有cookie正确

**Comment by huifeng-kooboo** [comment]
已处理 结束
